language: node_js
node_js:
 - 8
 - 10

before_install:
  - export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
  - sh -e /etc/init.d/xvfb start;
  - sleep 3;

install:
  - npm ci
  - npm run vscode:prepublish

script:
  - npm test --silent
